In [1]:
# Python3 program to solve N Queen  
# Problem using backtracking 
global N 
N = 4
  
def printSolution(board): 
    for i in range(N): 
        for j in range(N): 
            print (board[i][j], end = " ") 
        print() 
  
# A utility function to check if a queen can 
# be placed on board[row][col]. Note that this 
# function is called when "col" queens are 
# already placed in columns from 0 to col -1. 
# So we need to check only left side for 
# attacking queens 
def isSafe(board, row, col): 
  
    # Check this row on left side 
    for i in range(col): 
        if board[row][i] == 1: 
            return False
  
    # Check upper diagonal on left side 
    for i, j in zip(range(row, -1, -1),  
                    range(col, -1, -1)): 
        if board[i][j] == 1: 
            return False
  
    # Check lower diagonal on left side 
    for i, j in zip(range(row, N, 1),  
                    range(col, -1, -1)): 
        if board[i][j] == 1: 
            return False
  
    return True
  
def solveNQUtil(board, col): 
      
    # base case: If all queens are placed 
    # then return true 
    if col >= N: 
        return True
  
    # Consider this column and try placing 
    # this queen in all rows one by one 
    for i in range(N): 
  
        if isSafe(board, i, col): 
              
            # Place this queen in board[i][col] 
            board[i][col] = 1
  
            # recur to place rest of the queens 
            if solveNQUtil(board, col + 1) == True: 
                return True
  
            # If placing queen in board[i][col 
            # doesn't lead to a solution, then 
            # queen from board[i][col] 
            board[i][col] = 0
  
    # if the queen can not be placed in any row in 
    # this colum col then return false 
    return False
  
# This function solves the N Queen problem using 
# Backtracking. It mainly uses solveNQUtil() to 
# solve the problem. It returns false if queens 
# cannot be placed, otherwise return true and 
# placement of queens in the form of 1s. 
# note that there may be more than one 
# solutions, this function prints one of the 
# feasible solutions. 
def solveNQ(): 
    board = [ [0, 0, 0, 0], 
              [0, 0, 0, 0], 
              [0, 0, 0, 0], 
              [0, 0, 0, 0] ] 
  
    if solveNQUtil(board, 0) == False: 
        print ("Solution does not exist") 
        return False
  
    printSolution(board) 
    return True
  
# Driver Code 
solveNQ() 
  

0 0 1 0 
1 0 0 0 
0 0 0 1 
0 1 0 0 


True

In [2]:
def sudokutest(s,i,j,z):
    # z is the number
    isiValid = numpy.logical_or((i+1<1),(i+1>9));
    isjValid = numpy.logical_or((j+1<1),(j+1>9));
    iszValid = numpy.logical_or((z<1),(z>9));
    if s.shape!=(9,9):
        raise(Exception("Sudokumatrix not valid"));
    if isiValid:
        raise(Exception("i not valid"));
    if isjValid:
        raise(Exception("j not valid"));
    if iszValid:
        raise(Exception("z not valid"));

    if(s[i,j]!=0):
        return False;

    for ii in range(0,9):
        if(s[ii,j]==z):
            return False;

    for jj in range(0,9):
        if(s[i,jj]==z):
            return False;

    row = int(i/3) * 3;
    col = int(j/3) * 3;
    for ii in range(0,3):
        for jj in range(0,3):
            if(s[ii+row,jj+col]==z):
                return False;

    return True;

def possibleNums(s , i ,j):
    l = [];
    ind = 0;
    for k in range(1,10):
        if sudokutest(s,i,j,k):
            l.insert(ind,k);
            ind+=1;
    return l;

def sudokusolver(S):
    zeroFound = 0;
    for i in range(0,9):
        for j in range(0,9):
            if(S[i,j]==0):
                zeroFound=1;
                break;
        if(zeroFound==1):
            break;
    if(zeroFound==0):
        print("REALLY The end")
        z = numpy.zeros(shape=(9,9))
        for x in range(0,9):
            for y in range(0,9):
                z[x,y] = S[x,y]
        print(z)
        return z


    x = possibleNums(S,i,j);

    for k in range(len(x)):
        S[i,j]=x[k];
        sudokusolver(S);
    S[i,j] = 0;


if __name__ == "__main__":
    import numpy 
    #s = numpy.zeros(shape=(9,9))

    k = numpy.matrix([0,0,0,0,0,9,0,7,8,5,1,0,0,0,0,0,6,9,9,0,8,0,2,5,0,0,0,0,3,2,0,0,0,0,0,0,0,0,9,3,0,0,0,1,0,0,0,0,4,0,0,0,8,0,8,0,0,0,9,0,7,0,0,6,0,1,0,0,0,0,0,0,0,0,0,0,7,0,8,0,1]).reshape(9,9)
    print(k)
    print('*'*80)
    %timeit sudokusolver(k)

[[0 0 0 0 0 9 0 7 8]
 [5 1 0 0 0 0 0 6 9]
 [9 0 8 0 2 5 0 0 0]
 [0 3 2 0 0 0 0 0 0]
 [0 0 9 3 0 0 0 1 0]
 [0 0 0 4 0 0 0 8 0]
 [8 0 0 0 9 0 7 0 0]
 [6 0 1 0 0 0 0 0 0]
 [0 0 0 0 7 0 8 0 1]]
********************************************************************************
REALLY The end
[[3. 2. 4. 1. 6. 9. 5. 7. 8.]
 [5. 1. 7. 8. 3. 4. 2. 6. 9.]
 [9. 6. 8. 7. 2. 5. 1. 3. 4.]
 [1. 3. 2. 9. 8. 6. 4. 5. 7.]
 [4. 8. 9. 3. 5. 7. 6. 1. 2.]
 [7. 5. 6. 4. 1. 2. 9. 8. 3.]
 [8. 4. 3. 5. 9. 1. 7. 2. 6.]
 [6. 7. 1. 2. 4. 8. 3. 9. 5.]
 [2. 9. 5. 6. 7. 3. 8. 4. 1.]]
REALLY The end
[[3. 2. 4. 1. 6. 9. 5. 7. 8.]
 [5. 1. 7. 8. 3. 4. 2. 6. 9.]
 [9. 6. 8. 7. 2. 5. 1. 3. 4.]
 [1. 3. 2. 9. 8. 6. 4. 5. 7.]
 [4. 8. 9. 3. 5. 7. 6. 1. 2.]
 [7. 5. 6. 4. 1. 2. 9. 8. 3.]
 [8. 4. 3. 5. 9. 1. 7. 2. 6.]
 [6. 7. 1. 2. 4. 8. 3. 9. 5.]
 [2. 9. 5. 6. 7. 3. 8. 4. 1.]]


KeyboardInterrupt: 

In [3]:
import numpy as np
from functools import reduce

def solver_python(grid):
    numbers=np.arange(1,10)
    i,j = np.where(grid==0) 
    if (i.size==0):
        return(True,grid)
    else:
        i,j=i[0],j[0]    
        row = grid[i,:] 
        col = grid[:,j]
        sqr = grid[(i//3)*3:(3+(i//3)*3),(j//3)*3:(3+(j//3)*3)].reshape(9)
        values = np.setdiff1d(numbers,reduce(np.union1d,(row,col,sqr)))

        grid_temp = np.copy(grid) 

        for value in values:
            grid_temp[i,j] = value
            test = solver_python(grid_temp)
            if (test[0]):
                return(test)

        return(False,None)

example = np.array([[5,3,0,0,7,0,0,0,0],
                    [6,0,0,1,9,5,0,0,0],
                    [0,9,8,0,0,0,0,6,0],
                    [8,0,0,0,6,0,0,0,3],
                    [4,0,0,8,0,3,0,0,1],
                    [7,0,0,0,2,0,0,0,6],
                    [0,6,0,0,0,0,2,8,0],
                    [0,0,0,4,1,9,0,0,5],
                    [0,0,0,0,8,0,0,7,9]])

%timeit solver_python(example)

491 ms ± 1.38 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [1]:
import sys
import numpy as np
from functools import reduce

# Instructions:
# Linux>> python3 driver_3.py <soduku_str>
# Windows py3\> python driver_3.py <soduku_str>

# Inputs
# print("input was:", sys.argv)


def BT(soduku, slices):
    "Backtracking search to solve soduku"
    # If soduku is complete return it.
    if isComplete(soduku):
        return soduku
    # Select the MRV variable to fill
    vars = [tuple(e) for e in np.transpose(np.where(soduku==0))]
    var, avail_d = selectMRVvar(vars, soduku, slices)
    # Fill in a value and solve further (recursively), 
    # backtracking an assignment when stuck
    for value in avail_d:
        soduku[var] = value
        result = BT(soduku, slices)
        if np.any(result):
            return result
        else:
            soduku[var] = 0
    return False


def str2arr(soduku_str):
    "Converts soduku_str to 2d array"
    return np.array([int(s) for s in list(soduku_str)]).reshape((9,9))


def var2grid(var, slices):
    "Returns the grid slice (3x3) to which the variable's coordinates belong "
    row,col = var
    grid = ( slices[int(row/3)], slices[int(col/3)] )
    return grid


# Constraints
def unique_rows(soduku):
    for row in soduku:
        if not np.array_equal(np.unique(row),np.array(range(1,10))) :
            return False
    return True
def unique_columns(soduku):
    for row in soduku.T: #transpose soduku to get columns
        if not np.array_equal(np.unique(row),np.array(range(1,10))) :
            return False
    return True

def unique_grids(soduku, slices):
    s1,s2,s3 = slices
    allgrids=[(si,sj) for si in [s1,s2,s3] for sj in [s1,s2,s3]] # Makes 2d slices for grids
    for grid in allgrids: 
        if not np.array_equal(np.unique(soduku[grid]),np.array(range(1,10))) :
            return False
    return True

def  isComplete(soduku):
    if 0 in soduku:
        return False
    else:
        return True


def checkCorrect(soduku, slices):
    if unique_columns(soduku):
        if unique_rows(soduku):
            if unique_grids(soduku, slices):
                return True
    return False


# Search
def getDomain(var, soduku, slices):
    "Gets the remaining legal values (available domain) for an unfilled box `var` in `soduku`"
    row,col = var
    #ravail = np.setdiff1d(FULLDOMAIN, soduku[row,:])
    #cavail = np.setdiff1d(FULLDOMAIN, soduku[:,col])
    #gavail = np.setdiff1d(FULLDOMAIN, soduku[var2grid(var)])
    #avail_d = reduce(np.intersect1d, (ravail,cavail,gavail))
    used_d = reduce(np.union1d, (soduku[row,:], soduku[:,col], soduku[var2grid(var, slices)]))
    
    FULLDOMAIN = np.array(range(1,10)) #All possible values (1-9)
    avail_d = np.setdiff1d(FULLDOMAIN, used_d)
    #print(var, avail_d)
    return avail_d

def selectMRVvar(vars, soduku, slices):
    """
    Returns the unfilled box `var` with minimum remaining [legal] values (MRV) 
    and the corresponding values (available domain)
    """
    #Could this be improved?
    avail_domains = [getDomain(var,soduku, slices) for var in vars]
    avail_sizes = [len(avail_d) for avail_d in avail_domains]
    index = np.argmin(avail_sizes)
    return vars[index], avail_domains[index]




# Solve

def full_solution():
    soduku_str='000000000302540000050301070000000004409006005023054790000000050700810000080060009'

    soduku = str2arr(soduku_str)

    slices = [slice(0,3), slice(3,6), slice(6,9)]
    s1,s2,s3 = slices
    return BT(soduku, slices), soduku, slices

%timeit sol, soduku, slices = full_solution()
print("solved:\n", sol)
print("correct:", checkCorrect(soduku, slices))


351 ms ± 841 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


NameError: name 'sol' is not defined