# dataframe functions

In [3]:
import pandas as pd
import numpy as np

f = lambda x: np.abs(x)>1

df1 = pd.DataFrame([[1,0,-5],[2,0,-1],[1,4,0]])
df1[0][f(df1[0])] = "!1!"
print(df1)

df2 = pd.DataFrame([[1,0,-5],[2,0,-1],[1,4,0]])
df2[f(df2)] = "!2!"
print(df2)

     0  1  2
0    1  0 -5
1  !1!  0 -1
2    1  4  0
     0    1    2
0    1    0  !2!
1  !2!    0   -1
2    1  !2!    0


# numpy operations

In [4]:
import numpy as np

a = np.array([2]*4)
print(a)
b = np.array([1, 2, 3, 4, 5, 6, 7])
print(np.concatenate((a, b)))

j = [8, 7, 6, 5, 4, 3, 2, 1]
print ([x/j[-2] for x in j[1:-1]])


[2 2 2 2]
[2 2 2 2 1 2 3 4 5 6 7]
[3.5, 3.0, 2.5, 2.0, 1.5, 1.0]


# parse numpy

In [5]:
import numpy as np
import pandas as pd

x = np.array([[1,2,3,4],
             [4,5,6,7],
             [8,9,0,1]])

print ('x[0:2,[0,2]]', x[0:2,[0,2]])

print ('x[0:2,1:2]', x[0:2,1:2])

x[0:2,[0,2]] [[1 3]
 [4 6]]
x[0:2,1:2] [[2]
 [5]]


# change index

In [6]:
import numpy as np
import pandas as pd

dates = pd.date_range('2015-01-01', '2015-01-04', name='Date')
df = pd.DataFrame(index=dates)
df['count'] = [i for i in range(len(df))]

print (df)

df = df.reset_index(['Date'])
df.set_index('count', inplace=True)

print (df)

            count
Date             
2015-01-01      0
2015-01-02      1
2015-01-03      2
2015-01-04      3
            Date
count           
0     2015-01-01
1     2015-01-02
2     2015-01-03
3     2015-01-04


# numpy/pandas aggregation

In [7]:
import numpy as np
import pandas as pd

#18
a = np.random.randint(0,10,size=(3,3))
print ("Matrix a is ",a)
value = a.min(axis = 0)
print ("min is", value)

value = a.mean(axis = 0)
print ("mean is", value)


weekSales =  pd.DataFrame(np.random.random([7,3])*100,
            index=['Sun', 'Mon', 'Tues', 'Wed', 'Thurs', 'Fri', 'Sat'],
            columns=['Coffee', 'Donuts', 'Bagels'])

print (weekSales)
print (weekSales.sum(axis=0))

Matrix a is  [[2 9 1]
 [3 5 5]
 [4 4 1]]
min is [2 4 1]
mean is [3.         6.         2.33333333]
          Coffee     Donuts     Bagels
Sun    21.422299  92.720410  94.240209
Mon    50.611378  88.924402  18.890954
Tues   34.943291  35.110628  13.617225
Wed    66.154570  64.128298   8.548907
Thurs  85.356878   6.527219  92.760367
Fri    84.045903  64.480449  11.613591
Sat    66.082793  72.014752  47.237029
Coffee    408.617113
Donuts    423.906158
Bagels    286.908281
dtype: float64


# parsing multidimensional array

In [8]:
import numpy as np

ary = np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]])
print(ary)
print(ary[:, :, 0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 3]
 [5 7]]


# parsing in increments

In [9]:
import numpy as np

a = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20],
             [21,22,23,24,25]])

print(a[:,1:5:2])

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]
 [22 24]]


# multiplication

In [10]:
import numpy as np
a=np.ones((3,3))*2
print(a)

b=a.dot(a)
print(b)

c = np.multiply(a, b)
print(c)

d = a * b
print(d)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[12. 12. 12.]
 [12. 12. 12.]
 [12. 12. 12.]]
[[24. 24. 24.]
 [24. 24. 24.]
 [24. 24. 24.]]
[[24. 24. 24.]
 [24. 24. 24.]
 [24. 24. 24.]]


# join

In [11]:
df1 = pd.DataFrame( {'var1': [1,2,3,4,5], 'var2': [11,12,13,14,15]}, index = ['cat','dog', 'bird', 'fish', 'turtle'] )
df2 = pd.DataFrame( {'var3': [101,102,103,104,105]}, index = ['dog', 'bird', 'cat', 'turtle', 'fish'] )
df3 = df1.join(df2, how='left')
print (df3.loc['bird','var2'])

13


# filling values

In [12]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(5, 3), index=['2013-01-02', '2013-01-03', '2013-01-04', '2013-01-05', '2013-01-08'], columns=['a', 'b', 'c'])
df = df.reindex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04', '2013-01-05','2013-01-07', '2013-01-08', '2013-01-09'])

print(df.describe())
print(df.head(2))
print(df.tail(2))

print (df)
df.fillna(method='ffill', inplace=True)
df.fillna(method='bfill', inplace=True)
print (df)



              a         b         c
count  5.000000  5.000000  5.000000
mean   0.212307 -0.292524  0.266427
std    0.979677  0.401892  0.940294
min   -0.695988 -0.803210 -0.982310
25%   -0.600087 -0.654207 -0.156959
50%   -0.006341 -0.024160  0.154759
75%    0.720583  0.006006  0.846398
max    1.643367  0.012951  1.470246
                   a         b        c
2013-01-01       NaN       NaN      NaN
2013-01-02 -0.006341 -0.654207 -0.98231
                   a         b         c
2013-01-08 -0.600087  0.012951  1.470246
2013-01-09       NaN       NaN       NaN
                   a         b         c
2013-01-01       NaN       NaN       NaN
2013-01-02 -0.006341 -0.654207 -0.982310
2013-01-03 -0.695988 -0.024160  0.154759
2013-01-04  1.643367 -0.803210  0.846398
2013-01-05  0.720583  0.006006 -0.156959
2013-01-07       NaN       NaN       NaN
2013-01-08 -0.600087  0.012951  1.470246
2013-01-09       NaN       NaN       NaN
                   a         b         c
2013-01-01 -0.006341 -0

# dataframes need .copy() function like ndarrays and lists

In [13]:
import pandas as pd

df1 = pd.DataFrame({'Type': ["Stock", None]})
df2 = df1.copy()
df2.fillna("ETF", inplace=True)
print (df1)
print (df2)

df1 = pd.DataFrame({'Type': ["Stock", None]})
df2 = df1
df1.fillna("Mutual Fund", inplace=True)
print (df1)
print (df2)



    Type
0  Stock
1   None
    Type
0  Stock
1    ETF
          Type
0        Stock
1  Mutual Fund
          Type
0        Stock
1  Mutual Fund


# concat

In [14]:
import pandas as pd

# https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
        'B': ['B0', 'B1', 'B2', 'B3'],
        'C': ['C0', 'C1', 'C2', 'C3'],
        'D': ['D0', 'D1', 'D2', 'D3']},
        index=[0, 1, 2, 3])
print(df1)

df2 = pd.DataFrame({'B': ['B2', 'B3', 'B6', 'B7'],
        'D': ['D2', 'D3', 'D6', 'D7'],
        'F': ['F2', 'F3', 'F6', 'F7']},
        index=[2, 3, 6, 7])
print(df2)

frames = [df1, df2]
print(pd.concat(frames, sort=False))
print(pd.concat(frames, axis=1, join="inner"))

result = pd.concat(frames, keys=['x', 'y'], sort=False)
print(result)
print(result.loc['y'])

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
    B   D   F
2  B2  D2  F2
3  B3  D3  F3
6  B6  D6  F6
7  B7  D7  F7
     A   B    C   D    F
0   A0  B0   C0  D0  NaN
1   A1  B1   C1  D1  NaN
2   A2  B2   C2  D2  NaN
3   A3  B3   C3  D3  NaN
2  NaN  B2  NaN  D2   F2
3  NaN  B3  NaN  D3   F3
6  NaN  B6  NaN  D6   F6
7  NaN  B7  NaN  D7   F7
    A   B   C   D   B   D   F
2  A2  B2  C2  D2  B2  D2  F2
3  A3  B3  C3  D3  B3  D3  F3
       A   B    C   D    F
x 0   A0  B0   C0  D0  NaN
  1   A1  B1   C1  D1  NaN
  2   A2  B2   C2  D2  NaN
  3   A3  B3   C3  D3  NaN
y 2  NaN  B2  NaN  D2   F2
  3  NaN  B3  NaN  D3   F3
  6  NaN  B6  NaN  D6   F6
  7  NaN  B7  NaN  D7   F7
     A   B    C   D   F
2  NaN  B2  NaN  D2  F2
3  NaN  B3  NaN  D3  F3
6  NaN  B6  NaN  D6  F6
7  NaN  B7  NaN  D7  F7


# merge

In [15]:
import pandas as pd

# https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
        'B': ['B0', 'B1', 'B2', 'B3'],
        'C': ['C0', 'C1', 'C2', 'C3'],
        'D': ['D0', 'D1', 'D2', 'D3']},
        index=[0, 1, 2, 3])
print(df1)

df2 = pd.DataFrame({'B': ['B2', 'B3', 'B6', 'B7'],
        'D': ['D2', 'D3', 'D6', 'D7'],
        'F': ['F2', 'F3', 'F6', 'F7']},
        index=[2, 3, 6, 7])
print(df2)

result = pd.merge(df1, df2, how='right', on=['D', 'D'])
# can add this to ensure keys on both sides are the same: "validate='one_to_one'"
print(result)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
    B   D   F
2  B2  D2  F2
3  B3  D3  F3
6  B6  D6  F6
7  B7  D7  F7
     A  B_x    C   D B_y   F
0   A2   B2   C2  D2  B2  F2
1   A3   B3   C3  D3  B3  F3
2  NaN  NaN  NaN  D6  B6  F6
3  NaN  NaN  NaN  D7  B7  F7


# join

In [16]:
import pandas as pd

# https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html


left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                    index=['K0', 'K1', 'K2'])

print(left)
right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                       'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])
print(right)

result = left.join(right, how='outer')
print(result)

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2
     C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3
      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3


# groupby

In [17]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                           'foo', 'bar', 'foo', 'foo'],
                    'B' : ['one', 'one', 'two', 'three',
                           'two', 'two', 'one', 'three'],
                    'C' : np.random.randn(8),
                    'D' : np.random.randn(8)})

def get_letter_type(letter):
     if letter.lower() in 'aeiou':
        return 'vowel'
     else:
        return 'consonant'
    
grouped = df.groupby(get_letter_type, axis=1)

for key, item in grouped:
    print(grouped.get_group(key), "\n\n")
    
print(grouped.describe())

       B         C         D
0    one  0.887236 -0.009309
1    one -0.101233 -0.180797
2    two -1.575928 -1.209759
3  three -0.288650 -0.275517
4    two  2.054465  0.596064
5    two -1.158363 -0.433730
6    one -1.016523 -2.238945
7  three -0.224081  1.548680 


     A
0  foo
1  bar
2  foo
3  bar
4  foo
5  bar
6  foo
7  foo 


            count      mean      std      min       25%       50%       75%  \
consonant C     8 -0.177885  1.18064 -1.57593  -1.05198 -0.256366  0.145884   
          D     8 -0.275414  1.12885 -2.23894 -0.627737 -0.228157  0.142034   
vowel     A     8       NaN      NaN      NaN       NaN       NaN       NaN   

                 max unique  top freq  
consonant C  2.05447    NaN  NaN  NaN  
          D  1.54868    NaN  NaN  NaN  
vowel     A      NaN      2  foo    5  


# groupby 2

In [18]:
# https://pandas.pydata.org/pandas-docs/stable/getting_started/comparison/comparison_with_sql.html
import pandas as pd
import numpy as np
url = ('https://raw.github.com/pandas-dev/pandas/master/pandas/tests/data/tips.csv')
tips = pd.read_csv(url)

############ similar to:
# SELECT smoker, day, COUNT(*), AVG(tip)
# FROM tips
# GROUP BY smoker, day;

tips.groupby(['smoker', 'day']).agg({'tip': [np.size, np.mean]})

tip          
             size      mean
smoker day                 
No     Fri    4.0  2.812500
       Sat   45.0  3.102889
       Sun   57.0  3.167895
       Thur  45.0  2.673778
Yes    Fri   15.0  2.714000
       Sat   42.0  2.875476
       Sun   19.0  3.516842
       Thur  17.0  3.030000

# where

In [16]:
# https://pandas.pydata.org/pandas-docs/stable/getting_started/comparison/comparison_with_sql.html
import pandas as pd
url = ('https://raw.github.com/pandas-dev/pandas/master/pandas/tests/data/tips.csv')
tips = pd.read_csv(url)

tips = tips[(tips['size'] >= 5) | (tips['total_bill'] > 45)]
print(tips['tip'].iloc[0])
list_tips = list(tips['tip'].values)
print(list_tips)
list_tips.sort(reverse=True)
print(list_tips)

6.73
[6.73, 4.2, 6.7, 5.0, 5.0, 5.14, 5.0, 10.0, 3.5, 5.0, 2.0, 9.0, 3.0]
[10.0, 9.0, 6.73, 6.7, 5.14, 5.0, 5.0, 5.0, 5.0, 4.2, 3.5, 3.0, 2.0]


# location

In [20]:
import pandas as pd
df = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
        'B': ['B0', 'B1', 'B2', 'B3'],
        'C': ['C0', 'C1', 'C2', 'C3'],
        'D': ['D0', 'D1', 'D2', 'D3']},
        index=['zero', 'one', 'two', 'three'])

print('############# iloc #############')
print('')
print(df.iloc[:2]) # rows
print('')
print(df.iloc[-2:]) # rows
print('')
print(df.iloc[:, 2]) # cols
print('')
print(df.iloc[:2, :3]) # upper left
print('')

print('############# loc #############')
print('')
print(df.loc['zero'])
print('')
print(df.loc['one':'three']) # careful, this is inclusive unlike the rest of python!

print('############# columns #############')
print('')
print(df['B'])
print('')
print(df[['B', 'D']])
print('')

print('############# remove #############')
print('')
print(df.drop("B", axis=1))
print('')
print(df.drop("two", axis=0))

############# iloc #############

       A   B   C   D
zero  A0  B0  C0  D0
one   A1  B1  C1  D1

        A   B   C   D
two    A2  B2  C2  D2
three  A3  B3  C3  D3

zero     C0
one      C1
two      C2
three    C3
Name: C, dtype: object

       A   B   C
zero  A0  B0  C0
one   A1  B1  C1

############# loc #############

A    A0
B    B0
C    C0
D    D0
Name: zero, dtype: object

        A   B   C   D
one    A1  B1  C1  D1
two    A2  B2  C2  D2
three  A3  B3  C3  D3
############# columns #############

zero     B0
one      B1
two      B2
three    B3
Name: B, dtype: object

        B   D
zero   B0  D0
one    B1  D1
two    B2  D2
three  B3  D3

############# remove #############

        A   C   D
zero   A0  C0  D0
one    A1  C1  D1
two    A2  C2  D2
three  A3  C3  D3

        A   B   C   D
zero   A0  B0  C0  D0
one    A1  B1  C1  D1
three  A3  B3  C3  D3


# amax

In [21]:
import numpy as np

x= np.array([[1,2,3],[4,5,6], [7,8,9]])

y = np.amax(x, axis=1)
print(y)

[3 6 9]


# matrix

In [22]:
import numpy as np

a = np.matrix([[0,1,2,3],
               [4,5,6,7],
               [8,9,10,11],
               [12,13,14,15]])

a = a[::-1,::-1]

print (a[1:3,1:])

[[10  9  8]
 [ 6  5  4]]


# shift

In [23]:
import pandas as pd

data = {'A': [100, 60, 30, 130],
         'B': [5, 15, 15, 5],
         'C': [100, 300, 100, 200],
         'D': [20, 20, 30, 30]}
df = pd.DataFrame(data)
print(df)
df = df.shift(2, axis=1)
print(df)
print(df.mean())

     A   B    C   D
0  100   5  100  20
1   60  15  300  20
2   30  15  100  30
3  130   5  200  30
    A   B      C     D
0 NaN NaN  100.0   5.0
1 NaN NaN   60.0  15.0
2 NaN NaN   30.0  15.0
3 NaN NaN  130.0   5.0
A     NaN
B     NaN
C    80.0
D    10.0
dtype: float64


# columns

In [24]:
import pandas as pd

scala = pd.DataFrame(columns = ['Gold', 'Silver', 'USD', 'CAD'])
scala = scala.dropna(subset=['USD'])
scala = scala.rename(columns = {'Gold': 'AU'})
scala = scala.join(pd.DataFrame(columns = ['Copper']), how = 'left')
# joins rows together, all columns stay

print(scala.columns.tolist())

['AU', 'Silver', 'USD', 'CAD', 'Copper']


# reshape

In [25]:
import pandas as pd

# https://pandas.pydata.org/pandas-docs/stable/user_guide/reshaping.html#



# apply

In [26]:
import pandas as pd

d = {'AAPL' : pd.Series([615.99,626.63,621.64], index=['2012-04-02','2012-04-03','2012-04-04']),
     'GOOG' : pd.Series([646.92,642.62,635.15], index=['2012-04-02','2012-04-03','2012-04-04']),
     'MSFT' : pd.Series([31.87,31.52,30.80], index=['2012-04-02','2012-04-03','2012-04-04'])
    }
df1 = pd.DataFrame(d)

df2 = df1.apply(lambda x: x * 2)

result = df2 / df1

print(result)

            AAPL  GOOG  MSFT
2012-04-02   2.0   2.0   2.0
2012-04-03   2.0   2.0   2.0
2012-04-04   2.0   2.0   2.0


# apply 2

In [4]:
import pandas as pd

rectangles = [
    { 'height': 40, 'width': 10 },
    { 'height': 20, 'width': 9 },
    { 'height': 3.4, 'width': 4 }
]
rectangles_df = pd.DataFrame(rectangles)
print(rectangles_df)

def calculate_area(row):
    return row['height'] * row['width']

rectangles_df['area'] = None
rectangles_df['area'] = rectangles_df.apply(calculate_area, axis=1)
print(rectangles_df)

rectangles_df['area2'] = None
rectangles_df['area2'] = rectangles_df.apply(lambda row: row['height'] * row['width'], axis=1)
print(rectangles_df)

   height  width
0    40.0     10
1    20.0      9
2     3.4      4
   height  width   area
0    40.0     10  400.0
1    20.0      9  180.0
2     3.4      4   13.6
   height  width   area  area2
0    40.0     10  400.0  400.0
1    20.0      9  180.0  180.0
2     3.4      4   13.6   13.6


# apply 3 - true/false filtering

In [8]:
import pandas as pd

rectangles = [
    { 'height': 40, 'width': 10 },
    { 'height': 20, 'width': 9 },
    { 'height': 3.4, 'width': 4 }
]
rectangles_df = pd.DataFrame(rectangles)
print(rectangles_df)

def test_height(row):
    if row['height'] > 10:
        return True
    else:
        return False

rectangles_df = rectangles_df[rectangles_df.apply(test_height, axis=1)]
print(rectangles_df)

   height  width
0    40.0     10
1    20.0      9
2     3.4      4
   height  width
0    40.0     10
1    20.0      9


# arrange, reshape

In [28]:
import numpy as np

a = np.arange(6)
print(a)

print(a.reshape(6,1))
print(a.reshape(6,-5))
print(a.reshape(2,3))
print(a.reshape(2,3).T)

[0 1 2 3 4 5]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


# sort in order of QWERTY keyboard

In [29]:
def qwerty(inp): 
    alphabet = 'qwertyuiopasdfghjklzxcvbnm'
    a_list = list(alphabet)

    num_alpha = []
    for i in range(len(inp)):
        for j in range(len(a_list)):
            if inp[i] == a_list[j]:
                num_alpha.append(j)
    
    num_alpha.sort()
    fin = []
    for i in range(len(num_alpha)):
        fin.append(a_list[num_alpha[i]])
    
    return ''.join(fin)

print (qwerty('supercalifragilistic expialidocious'))

qwerty2 = lambda x: ''.join(sorted(x, key=lambda l: 'qwertyuiopasdfghjklzxcvbnm'.index(l)))
print(qwerty2('supercalifragilisticexpialidocious'))

qwerty3 = lambda x: ' '.join(map(lambda i: ''.join(sorted(i, key=lambda l: 'qwertyuiopasdfghjklzxcvbnm'.index(l[0]))), x.split(' ')))
print(qwerty3('supercalifragil isticexpi alidocious'))

eerrtuuiiiiiiiooppaaasssdfglllxccc
eerrtuuiiiiiiiooppaaasssdfglllxccc
erruiipaasfgllc etiiipsxc uiiooasdlc


# pandas manipulation

In [30]:
a = [1.1 ** i for i in range(0,5)]

dvs = pd.DataFrame(a)
print(dvs)
print(dvs[0])

drs = dvs[0] / dvs[0].shift(1) - 1
print(drs)

print([round(num, 1) for num in drs])

        0
0  1.0000
1  1.1000
2  1.2100
3  1.3310
4  1.4641
0    1.0000
1    1.1000
2    1.2100
3    1.3310
4    1.4641
Name: 0, dtype: float64
0    NaN
1    0.1
2    0.1
3    0.1
4    0.1
Name: 0, dtype: float64
[nan, 0.1, 0.1, 0.1, 0.1]
